location /feeding/ {
    alias /var/www/html/feeding/;
    try_files $uri $uri/ /feeding/index.html;
}

location /api/ {
    alias /var/www/html/api/;
    default_type application/json;
    add_header Cache-Control "no-cache";
    add_header Access-Control-Allow-Origin "*";
    try_files $uri =404;
}
